# -*- coding: utf-8 -*-
"""step 1 (flames game).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MdJ3PS33ItMBX6w7EjZcRnoNb1n50pW7
"""

# function for removing common characters
# with their respective occurrences
def remove_match_char(list1, list2):
      for i in range(len(list1)) :
        for j in range(len(list2)) :
 
            # if common character is found
            # then remove that character
            # and return list of concatenated
            # list with True Flag
            if list1[i] == list2[j] :
                c = list1[i]
 
                # remove character from the list
                list1.remove(c)
                list2.remove(c)
 
                # concatenation of two list elements with *
                # * is act as border mark here
                list3 = list1 + ["*"] + list2
 
                # return the concatenated list with True flag
                return [list3, True]
 
    # no common characters is found
    # return the concatenated list with False flag
    list3 = list1 + ["*"] + list2
    return [list3, False]
 if __name__ == "__main__" : 
    N1=str(input("Enter your name: ")
    N1 = N1.lower()
    list1=string.split(N1)
    N2=str(input("Enter your name: "))
    N2=N2.lower()
    list2=string.split(N2)
    roceed = True
    while proceed :
        ret_list = remove_match_char(list1, list2)
        con_list = ret_list[0]
        proceed = ret_list[1]
        star_index = con_list.index("*")
        list1 = con_list[ : star_index]
        list2 = con_list[star_index + 1 : ]
    count = len(list1) + len(list2)
    result = ["Friends", "Love", "Affection", "Marriage", "Enemy", "Siblings"]
    while len(result) > 1 :
        split_index = (count % len(result) - 1)
        if split_index >= 0 :
            right = result[split_index + 1 : ]
            left = result[ : split_index]
            result = right + left
        else :
            result = result[ : len(result) - 1]
 print("Relationship status :", result[0])